source 'https://rubygems.org'
ruby "~> 3.2.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
gem 'sinatra'
gem 'webrick'
gem 'thin'
gem 'falcon'
gem 'puma'
gem 'dotenv'
gem 'httparty'
gem 'json'
gem 'launchy'